name: fitnet-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.24.3
  - pandas=1.5.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - plotly=5.14.1
  - dash=2.11.1
  - flask=2.2.3
  - opencv=4.7.0
  - scikit-learn=1.2.2
  - pip
  - pip:
      - torch==2.0.1
      - torchvision==0.15.2